version: "3"
services:
  web:
    image: igordubinin/nodeapp:v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 1400M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:8080"
    networks:
      - webnet
networks:
  webnet: